id: McAfee ESM v2 - Test
version: -1
contentitemfields:
  propagationLabels: []
name: McAfee ESM v2 - Test
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: 6c85c7f9-79e8-4c47-8f3e-ed0829043436
    type: start
    task:
      id: 6c85c7f9-79e8-4c47-8f3e-ed0829043436
      version: -1
      name: ''
      iscommand: false
      description: ''
    nexttasks:
      '#none#':
      - '2'
      - '5'
      - '7'
      - '10'
      - '14'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: 74fef4c8-89b0-4205-88b8-9d3194ce9470
    type: regular
    task:
      id: 74fef4c8-89b0-4205-88b8-9d3194ce9470
      version: -1
      name: get_user_list
      description: ''
      script: '|||esm-get-user-list'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '3'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: 72596641-c90d-49c3-8581-2bd3bf84fa63
    type: regular
    task:
      id: 72596641-c90d-49c3-8581-2bd3bf84fa63
      version: -1
      name: get_organization_list
      description: ''
      script: '|||esm-get-organization-list'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '1'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '3':
    id: '3'
    taskid: 321419e2-cf89-4b02-88f7-47621c7974e0
    type: regular
    task:
      id: 321419e2-cf89-4b02-88f7-47621c7974e0
      version: -1
      name: get_case_list
      description: ''
      script: '|||esm-get-case-list'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '4'
    scriptarguments:
      since:
        simple: 3 months
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: 2694f7e2-a958-4d35-8235-2ebef5d31dfc
    type: regular
    task:
      id: 2694f7e2-a958-4d35-8235-2ebef5d31dfc
      version: -1
      name: get_case_statuses
      description: ''
      script: '|||esm-get-case-statuses'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '13'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '5':
    id: '5'
    taskid: 9916bdac-ccab-4bb2-8e6c-4a6a174daed2
    type: regular
    task:
      id: 9916bdac-ccab-4bb2-8e6c-4a6a174daed2
      version: -1
      name: add_case
      description: ''
      script: '|||esm-add-case'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      assignee: {}
      organization: {}
      severity: {}
      status: {}
      summary:
        simple: McAfee ESM v2 add case test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: faf090e4-8b64-41fa-809c-0157f80b806c
    type: regular
    task:
      id: faf090e4-8b64-41fa-809c-0157f80b806c
      version: -1
      name: edit_case
      description: ''
      script: '|||esm-edit-case'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '13'
    scriptarguments:
      assignee: {}
      id:
        simple: ${Case.ID}
      organization: {}
      severity: {}
      status: {}
      summary:
        simple: McAfee v2 edit case test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '7':
    id: '7'
    taskid: be8598d9-8f07-41c0-8ffa-99e9b51f2f74
    type: regular
    task:
      id: be8598d9-8f07-41c0-8ffa-99e9b51f2f74
      version: -1
      name: add_case_status
      description: ''
      script: '|||esm-add-case-status'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '8'
    scriptarguments:
      name:
        simple: AAA
      show_in_case_pane: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '8':
    id: '8'
    taskid: a7d57d20-5894-419d-8f23-9100e32133f6
    type: regular
    task:
      id: a7d57d20-5894-419d-8f23-9100e32133f6
      version: -1
      name: edit_case_status
      description: ''
      script: '|||esm-edit-case-status'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '9'
    scriptarguments:
      new_name:
        simple: BBB
      original_name:
        simple: AAA
      show_in_case_pane: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '9':
    id: '9'
    taskid: 796ee327-acba-4a41-8b4f-3398254d0ea0
    type: regular
    task:
      id: 796ee327-acba-4a41-8b4f-3398254d0ea0
      version: -1
      name: delete_case_status
      description: ''
      script: '|||esm-delete-case-status'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '13'
    scriptarguments:
      name:
        simple: BBB
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '10':
    id: '10'
    taskid: e2c9cbc2-042f-48f7-8aa3-9da384fef5c6
    type: regular
    task:
      id: e2c9cbc2-042f-48f7-8aa3-9da384fef5c6
      version: -1
      name: search
      description: ''
      script: '|||esm-search'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '11'
    scriptarguments:
      customEnd: {}
      customStart: {}
      fields: {}
      filters:
        simple: '[{"type":"EsmFieldFilter","field":{"name":"SrcIP"},"operator":"IN"}]'
      limit:
        simple: '30'
      queryType: {}
      timeOut: {}
      timeRange:
        simple: CURRENT_YEAR
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '11':
    id: '11'
    taskid: 3b17b873-5b14-40e8-811a-3f8552100403
    type: regular
    task:
      id: 3b17b873-5b14-40e8-811a-3f8552100403
      version: -1
      name: get_alarm_event_details
      description: ''
      script: '|||esm-get-alarm-event-details'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      eventId:
        simple: ${McAfeeESM.[0].AlertIPSIDAlertID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '12':
    id: '12'
    taskid: 5b5cb169-549d-40e8-8e72-126070ab2d20
    type: regular
    task:
      id: 5b5cb169-549d-40e8-8e72-126070ab2d20
      version: -1
      name: get_case_event_list
      description: ''
      script: '|||esm-get-case-event-list'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '13'
    scriptarguments:
      ids:
        simple: ${McAfeeESM.[0].AlertIPSIDAlertID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '13':
    id: '13'
    taskid: ebc94931-e657-4f4d-80ec-aca375b4cc2a
    type: title
    task:
      id: ebc94931-e657-4f4d-80ec-aca375b4cc2a
      version: -1
      name: done
      type: title
      iscommand: false
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 250,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '14':
    id: '14'
    taskid: 4839ab10-25de-4f2e-8b82-96f8a2997a94
    type: regular
    task:
      id: 4839ab10-25de-4f2e-8b82-96f8a2997a94
      version: -1
      name: fetch_alarms
      description: ''
      script: esm-fetch-alarms
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '15'
    scriptarguments:
      assignedUser: {}
      customEnd: {}
      customStart: {}
      timeRange:
        simple: CURRENT_YEAR
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -750,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '15':
    id: '15'
    taskid: ab28365b-bd3d-4893-8585-92887f1dab3e
    type: regular
    task:
      id: ab28365b-bd3d-4893-8585-92887f1dab3e
      version: -1
      name: acknowledge_alarms
      description: ''
      script: '|||esm-acknowledge-alarms'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '16'
    scriptarguments:
      alarmIds:
        simple: ${Alarm.[0].ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -750,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '16':
    id: '16'
    taskid: 85a6c1ef-e779-4b05-8898-ec8d84104c37
    type: regular
    task:
      id: 85a6c1ef-e779-4b05-8898-ec8d84104c37
      version: -1
      name: unacknowledge_alarms
      description: ''
      script: '|||esm-unacknowledge-alarms'
      type: regular
      iscommand: true
    nexttasks:
      '#none#':
      - '13'
    scriptarguments:
      alarmIds:
        simple: ${Alarm.[0].ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -750,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 1980,
        "x": -750,
        "y": 40
      }
    }
  }
inputs: []
outputs: []
description: ''
