id: PAN-OS EDL Setup v2 Test
version: -1
name: PAN-OS EDL Setup v2 Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9ff3057c-2050-4220-83b4-42aaf61599db
    type: start
    task:
      id: 9ff3057c-2050-4220-83b4-42aaf61599db
      version: -1
      name: ""
      description: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: fefbc0c9-1298-4e7e-8538-e6d1464b59b6
    type: regular
    task:
      id: fefbc0c9-1298-4e7e-8538-e6d1464b59b6
      version: -1
      name: find external file
      description: Gets metadata for an external file.
      script: '|||pan-os-edl-get-external-file-metadata'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      file_path:
        complex:
          root: inputs.list-name
          transformers:
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: .txt
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: a1e0a12d-9913-41e9-8bed-1d634529405a
    type: condition
    task:
      id: a1e0a12d-9913-41e9-8bed-1d634529405a
      version: -1
      name: is the external file exists
      description: checks if the external file exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: containsGeneral
          left:
            value:
              simple: PANOSEDL.FileName
            iscontext: true
          right:
            value:
              complex:
                root: inputs.list-name
                transformers:
                - operator: concat
                  args:
                    prefix: {}
                    suffix:
                      value:
                        simple: .txt
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: b2c51b11-68c3-4834-8bb7-fa33251ea7ac
    type: title
    task:
      id: b2c51b11-68c3-4834-8bb7-fa33251ea7ac
      version: -1
      name: Done
      description: ""
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: bef5aa07-dd9a-4bdc-831b-48bac3ed496e
    type: regular
    task:
      id: bef5aa07-dd9a-4bdc-831b-48bac3ed496e
      version: -1
      name: Dump internal list content to context
      description: Dumps (copies) instance context to either the incident context
      script: '|||pan-os-edl-dump-internal-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      destination:
        simple: incident_context
      list_name:
        simple: ${inputs.list-name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 3820fffd-4d56-4cf5-816a-74fe1b223bf4
    type: condition
    task:
      id: 3820fffd-4d56-4cf5-816a-74fe1b223bf4
      version: -1
      name: Check if internal list exists
      description: Checks whether the internal list exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "6"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOSEDL.ListName
            iscontext: true
          right:
            value:
              simple: inputs.list-name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 0b78d4ef-6714-41c1-80ad-d353f38bbfb2
    type: regular
    task:
      id: 0b78d4ef-6714-41c1-80ad-d353f38bbfb2
      version: -1
      name: Clear Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 16f52769-c9d4-4685-80aa-d8ef8dc807c5
    type: regular
    task:
      id: 16f52769-c9d4-4685-80aa-d8ef8dc807c5
      version: -1
      name: Dump internal list content to context
      description: Dumps (copies) instance context to either the incident context
        or a file.
      script: '|||pan-os-edl-dump-internal-list'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      destination:
        simple: incident_context
      list_name:
        simple: ${inputs.list-name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 9388f001-353e-4941-80a2-f78fbf1c410a
    type: regular
    task:
      id: 9388f001-353e-4941-80a2-f78fbf1c410a
      version: -1
      name: Clear Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: eb08bb55-8efe-461e-898f-b9f35aea4693
    type: condition
    task:
      id: eb08bb55-8efe-461e-898f-b9f35aea4693
      version: -1
      name: Check if internal list exists
      description: Checks whether the internal list exists
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: PANOSEDL.ListName
            iscontext: true
          right:
            value:
              simple: inputs.list-name
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: ed14bfc4-a945-4f5a-89ae-ca68bb6ff90d
    type: playbook
    task:
      id: ed14bfc4-a945-4f5a-89ae-ca68bb6ff90d
      version: -1
      name: PAN-OS EDL Setup_V2
      playbookName: PAN-OS EDL Setup_V2
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      action-type:
        simple: drop
      auto-commit:
        simple: "Yes"
      device-group: {}
      inbound-or-outbound-rule:
        simple: outbound
      ioc-type:
        simple: ip
      list-items:
        simple: 1.1.1.1
      list-name:
        simple: ip2022
      log-forwarding-object-name: {}
      pre-post-rulebase:
        simple: pre-rulebase
      relative-rule-name: {}
      rule-name:
        simple: rule-test-2022
      rule-position:
        simple: bottom
      web-server-ip:
        simple: 18.219.190.57
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1785,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: list-name
  value:
    simple: ip2020
  required: false
  description: the name of the external file
- key: list-items
  value:
    simple: 1.1.1.1
  required: false
  description: ""
outputs: []
