id: BlueCoatProxySGTest
version: -1
contentitemfields:
  propagationLabels: []
name: BlueCoatProxySGTest
starttaskid: '0'
tasks:
  '0':
    id: '0'
    taskid: f5a22f06-82b3-4c33-8871-477cbd7561a9
    type: start
    task:
      id: f5a22f06-82b3-4c33-8871-477cbd7561a9
      version: -1
      name: ''
      iscommand: false
      brand: ''
      description: ''
    nexttasks:
      '#none#':
      - '8'
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '1':
    id: '1'
    taskid: f7253db8-6354-49bb-8ef4-85a161316785
    type: regular
    task:
      id: f7253db8-6354-49bb-8ef4-85a161316785
      version: -1
      name: proxy-filter-add-url http://woo.demisto.com
      description: Add a URL to the proxy filter list
      script: Proxy URL Filter Server|||proxy-filter-add-url
      type: regular
      iscommand: true
      brand: Proxy URL Filter Server
    nexttasks:
      '#none#':
      - '2'
    scriptarguments:
      category: {}
      url:
        simple: http://woo.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '2':
    id: '2'
    taskid: eb4657dd-02d5-4304-8459-e6c723d5dbfd
    type: regular
    task:
      id: eb4657dd-02d5-4304-8459-e6c723d5dbfd
      version: -1
      name: get url from proxy list
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '3'
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: http://0.0.0.0:7000
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '3':
    id: '3'
    taskid: f6ee024e-196c-45c6-80bb-030c2312a6a1
    type: condition
    task:
      id: f6ee024e-196c-45c6-80bb-030c2312a6a1
      version: -1
      name: Check that the blacklist contains http://woo.demisto.com
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '4'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: containsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://woo.demisto.com
      - - operator: notContainsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://foo.demisto.com
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '4':
    id: '4'
    taskid: b0b351b6-25eb-4d54-83f0-d04f8c426523
    type: regular
    task:
      id: b0b351b6-25eb-4d54-83f0-d04f8c426523
      version: -1
      name: proxy-filter-add-url  http://foo.demisto.com
      description: Add a URL to the proxy filter list
      script: '|||proxy-filter-add-url'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '7'
    scriptarguments:
      category: {}
      url:
        simple: http://foo.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '5':
    id: '5'
    taskid: 637ab4f5-7c00-41bb-84fc-2eb1f8d6ab37
    type: regular
    task:
      id: 637ab4f5-7c00-41bb-84fc-2eb1f8d6ab37
      version: -1
      name: get url from proxy list
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '6'
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: http://0.0.0.0:7000
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '6':
    id: '6'
    taskid: 42f1bc46-5d57-4a4c-8441-7c1ebb4875ce
    type: condition
    task:
      id: 42f1bc46-5d57-4a4c-8441-7c1ebb4875ce
      version: -1
      name: Check that the blacklist contains both http://woo.demisto.com and http://foo.demisto.com
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '9'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: containsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://woo.demisto.com
      - - operator: containsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://foo.demisto.com
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '7':
    id: '7'
    taskid: a003c5cb-4ffa-4729-8b80-23cbc34edc46
    type: regular
    task:
      id: a003c5cb-4ffa-4729-8b80-23cbc34edc46
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '5'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '8':
    id: '8'
    taskid: 4015115a-a0b0-41ad-8295-b74313444527
    type: regular
    task:
      id: 4015115a-a0b0-41ad-8295-b74313444527
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '1'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '9':
    id: '9'
    taskid: 2afad39a-b32e-4748-8e82-0e2a0f7c9b17
    type: regular
    task:
      id: 2afad39a-b32e-4748-8e82-0e2a0f7c9b17
      version: -1
      name: proxy-filter-del-url http://foo.demisto.com
      description: Remove a URL from the proxy filter list
      script: '|||proxy-filter-del-url'
      type: regular
      iscommand: true
      brand: ''
    nexttasks:
      '#none#':
      - '10'
    scriptarguments:
      category: {}
      url:
        simple: http://foo.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '10':
    id: '10'
    taskid: cf0d717e-fd13-45e1-8fac-379719ec00a1
    type: regular
    task:
      id: cf0d717e-fd13-45e1-8fac-379719ec00a1
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '11'
    scriptarguments:
      all:
        simple: 'yes'
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '11':
    id: '11'
    taskid: 6b10b351-6266-441f-8f70-46c48ba0e63e
    type: regular
    task:
      id: 6b10b351-6266-441f-8f70-46c48ba0e63e
      version: -1
      name: get url from proxy list
      description: Sends http request. Returns the response as json.
      scriptName: http
      type: regular
      iscommand: false
      brand: ''
    nexttasks:
      '#none#':
      - '12'
    scriptarguments:
      body: {}
      filename: {}
      headers: {}
      insecure: {}
      method:
        simple: GET
      password: {}
      proxy: {}
      saveAsFile: {}
      unsecure: {}
      url:
        simple: http://0.0.0.0:7000
      username: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '12':
    id: '12'
    taskid: 420a635b-3631-4c09-8267-9e4e6ded1e8f
    type: condition
    task:
      id: 420a635b-3631-4c09-8267-9e4e6ded1e8f
      version: -1
      name: Check that the blacklist contains http://woo.demisto.com
      type: condition
      iscommand: false
      brand: ''
    nexttasks:
      'yes':
      - '13'
    separatecontext: false
    conditions:
    - label: 'yes'
      condition:
      - - operator: containsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://woo.demisto.com
      - - operator: notContainsString
          left:
            value:
              simple: ${HttpRequest.Response.Body}
            iscontext: true
          right:
            value:
              simple: http://foo.demisto.com
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  '13':
    id: '13'
    taskid: 5d2e8bb7-880e-472a-8a77-84bca9b34d05
    type: title
    task:
      id: 5d2e8bb7-880e-472a-8a77-84bca9b34d05
      version: -1
      name: Test Done
      type: title
      iscommand: false
      brand: ''
      description: ''
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2295
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2310,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
