id: playbook McAfee ESM v2 - Test
version: 2
contentitemfields:
  propagationLabels: []
name: playbook McAfee ESM v2 - Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9728c55d-02fb-43fa-8a9c-8e806ecb2b24
    type: start
    task:
      id: 9728c55d-02fb-43fa-8a9c-8e806ecb2b24
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
      - "5"
      - "7"
      - "10"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 250,
          "y": 40
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 94c3d75e-f195-4dcc-8f08-69c5234e785d
    type: regular
    task:
      id: 94c3d75e-f195-4dcc-8f08-69c5234e785d
      version: -1
      name: get_user_list
      description: Get a list of all users.
      script: esm-get-user-list
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "3"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 06f0a3ef-476c-4f4f-8f82-7aacfdc1b49a
    type: regular
    task:
      id: 06f0a3ef-476c-4f4f-8f82-7aacfdc1b49a
      version: -1
      name: get_organization_list
      description: Get case organization
      script: esm-get-organization-list
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: 2ac1607f-6d14-48cc-8573-ab2817911598
    type: regular
    task:
      id: 2ac1607f-6d14-48cc-8573-ab2817911598
      version: -1
      name: get_case_list
      description: Get a list of cases from the system
      script: esm-get-case-list
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      since:
        simple: 3 months
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 0e9481d1-7bb8-4657-8b9d-c0e9fd6ed21d
    type: regular
    task:
      id: 0e9481d1-7bb8-4657-8b9d-c0e9fd6ed21d
      version: -1
      name: get_case_statuses
      description: Get a list of valid case statuses from the system
      script: esm-get-case-statuses
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "13"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 850,
          "y": 590
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: cfbc2dc2-b0c3-4135-8fe9-66f0ea2f85e6
    type: regular
    task:
      id: cfbc2dc2-b0c3-4135-8fe9-66f0ea2f85e6
      version: -1
      name: add_case
      description: Add a case to the system
      script: esm-add-case
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      assignee: {}
      organization: {}
      severity: {}
      status: {}
      summary:
        simple: McAfee ESM v2 add case test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: b0bb5e4a-8b77-4d5f-857d-3044b6d447d6
    type: regular
    task:
      id: b0bb5e4a-8b77-4d5f-857d-3044b6d447d6
      version: -1
      name: edit_case
      description: Edit an existing case
      script: esm-edit-case
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      assignee: {}
      id:
        simple: ${Case.ID}
      organization: {}
      severity: {}
      status: {}
      summary:
        simple: McAfee v2 edit case test
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 76a92c67-ef0b-4d96-865c-73fae687dc25
    type: regular
    task:
      id: 76a92c67-ef0b-4d96-865c-73fae687dc25
      version: -1
      name: add_case_status
      description: Add a case status
      script: McAfee ESM_v2|||esm-add-case-status
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      name:
        simple: McAfee_ESM_v2_add_case
      show_in_case_pane: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: c46a1584-0204-4abe-82e3-318924c9cf4f
    type: regular
    task:
      id: c46a1584-0204-4abe-82e3-318924c9cf4f
      version: -1
      name: edit_case_status
      description: Edit a case status
      script: McAfee ESM_v2|||esm-edit-case-status
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      new_name:
        simple: TestMcAfee_ESM_v2_edit
      original_name:
        simple: McAfee_ESM_v2_add_case
      show_in_case_pane: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: e1dc4614-af98-4b70-8148-e44c746e91e8
    type: regular
    task:
      id: e1dc4614-af98-4b70-8148-e44c746e91e8
      version: -1
      name: delete_case_status
      description: Delete a case status
      script: esm-delete-case-status
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      name:
        simple: TestMcAfee_ESM_v2_edit
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: b0598432-33bb-4e3e-8f45-fce688b38cf9
    type: regular
    task:
      id: b0598432-33bb-4e3e-8f45-fce688b38cf9
      version: -1
      name: search
      description: Perform a query against Mcafee ESM SIEM
      script: McAfee ESM_v2|||esm-search
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      customEnd: {}
      customStart: {}
      fields: {}
      filters:
        simple: '[{"type":"EsmFieldFilter","field":{"name":"SrcIP"},"operator":"IN"}]'
      limit:
        simple: "30"
      queryType: {}
      timeOut: {}
      timeRange:
        simple: PREVIOUS_QUARTER
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: db4d73dd-d811-4bbf-87cb-32c718f2b1f1
    type: regular
    task:
      id: db4d73dd-d811-4bbf-87cb-32c718f2b1f1
      version: -1
      name: get_alarm_event_details
      description: Gets the details for the triggered alarm
      script: '|||esm-get-alarm-event-details'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      eventId:
        simple: ${McAfeeESM.[0].Alert.IPSIDAlertID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 310
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: b3a7339a-1fd9-482a-8f36-f910940e9b63
    type: regular
    task:
      id: b3a7339a-1fd9-482a-8f36-f910940e9b63
      version: -1
      name: get_case_event_list
      description: Get case events details
      script: esm-get-case-event-list
      type: regular
      iscommand: true
      brand: McAfee ESM_v2
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      ids:
        simple: ${McAfeeESM.[0].Alert.IPSIDAlertID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": -350,
          "y": 450
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 45a50235-b396-425d-8979-a763c64b67ce
    type: title
    task:
      id: 45a50235-b396-425d-8979-a763c64b67ce
      version: -1
      name: done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 250,
          "y": 760
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 1580,
        "x": -350,
        "y": 40
      }
    }
  }
inputs: []
outputs: []
