id: TestCofenseFeed
version: -1
contentitemfields:
  propagationLabels: []
name: TestCofenseFeed
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: ce8e21a4-f8a4-4347-8ae7-efc7cae88a5b
    type: start
    task:
      id: ce8e21a4-f8a4-4347-8ae7-efc7cae88a5b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: d73683d4-fa80-4c32-8d8d-313ad9bc6c56
    type: regular
    task:
      id: d73683d4-fa80-4c32-8d8d-313ad9bc6c56
      version: -1
      name: get-indicators
      description: Get indicators
      script: Cofense Feed|||get-indicators
      type: regular
      iscommand: true
      brand: Cofense Feed
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      from_time:
        simple: 1 year
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: bb4a7b8a-58a2-4fe4-8f0d-cb9edc079d36
    type: condition
    task:
      id: bb4a7b8a-58a2-4fe4-8f0d-cb9edc079d36
      version: -1
      name: Validate there's something inside.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "3"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isNotEmpty
          left:
            value:
              complex:
                root: Cofense
                accessor: Indicator
            iscontext: true
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: 76bac657-5af2-40a1-888c-d80aee2e6152
    type: title
    task:
      id: 76bac657-5af2-40a1-888c-d80aee2e6152
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: 07a4814e-6525-4c9d-88eb-4913f0fb24aa
    type: regular
    task:
      id: 07a4814e-6525-4c9d-88eb-4913f0fb24aa
      version: -1
      name: Raise error
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      message:
        simple: Got nothing from the feed. Maybe we need to expand the years of pulling.
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "5":
    id: "5"
    taskid: cda984b7-3eab-4001-8e91-841734972635
    type: regular
    task:
      id: cda984b7-3eab-4001-8e91-841734972635
      version: -1
      name: Delete Context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 910,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
