elasticcommonfields: {}
id: Tanium Threat Response Test
version: -1
contentitemexportablefields:
  contentitemfields:
    propagationLabels:
    - all
name: Tanium Threat Response Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 6278e87f-fa60-4cde-83df-e7720c48f817
    type: start
    task:
      elasticcommonfields: {}
      id: 6278e87f-fa60-4cde-83df-e7720c48f817
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 54ddd52d-add1-42bc-8342-4d85c7bb0630
    type: regular
    task:
      elasticcommonfields: {}
      id: 54ddd52d-add1-42bc-8342-4d85c7bb0630
      version: -1
      name: Clear context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "4"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: f6d15e03-7a32-4596-860a-eb0ea740ac20
    type: regular
    task:
      elasticcommonfields: {}
      id: f6d15e03-7a32-4596-860a-eb0ea740ac20
      version: -1
      name: Get intel doc by ID
      description: Returns a intel document object based on ID.
      script: '|||tanium-tr-get-intel-doc-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      intel-doc-id:
        simple: "64"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 97818479-4c8f-418b-8003-7be429255f3f
    type: title
    task:
      elasticcommonfields: {}
      id: 97818479-4c8f-418b-8003-7be429255f3f
      version: -1
      name: Query lists commands
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "4":
    id: "4"
    taskid: 940d6cf8-123c-4e97-8afa-057bb27d3024
    type: title
    task:
      elasticcommonfields: {}
      id: 940d6cf8-123c-4e97-8afa-057bb27d3024
      version: -1
      name: Getters
      type: title
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "5":
    id: "5"
    taskid: fecdad65-22f8-4780-854d-092c8325f318
    type: regular
    task:
      elasticcommonfields: {}
      id: fecdad65-22f8-4780-854d-092c8325f318
      version: -1
      name: Get intel docs list
      description: Returns a list of all intel documents.
      script: '|||tanium-tr-list-intel-docs'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 515
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "6":
    id: "6"
    taskid: 3c7b3083-c3b8-4505-8b63-d6d387b5c029
    type: regular
    task:
      elasticcommonfields: {}
      id: 3c7b3083-c3b8-4505-8b63-d6d387b5c029
      version: -1
      name: Get alerts list
      description: Returns a list of all alerts.
      script: '|||tanium-tr-list-alerts'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      computer-ip-address: {}
      computer-name: {}
      intel-doc-id: {}
      limit: {}
      offset: {}
      priority: {}
      scan-config-id: {}
      severity: {}
      state: {}
      type: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "7":
    id: "7"
    taskid: 203af7e8-b592-4c8c-84d1-c314a82d8a24
    type: regular
    task:
      elasticcommonfields: {}
      id: 203af7e8-b592-4c8c-84d1-c314a82d8a24
      version: -1
      name: Get connections list
      description: Returns all connections.
      script: '|||tanium-tr-list-connections'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "8":
    id: "8"
    taskid: 7dffb4b4-6c9e-44f8-8451-26137ae3eba4
    type: regular
    task:
      elasticcommonfields: {}
      id: 7dffb4b4-6c9e-44f8-8451-26137ae3eba4
      version: -1
      name: Get snapshots list
      description: Returns all snapshots.
      script: '|||tanium-tr-list-snapshots'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "9":
    id: "9"
    taskid: c08ef6f1-f7e8-498e-8a55-7ad1ea21aabd
    type: regular
    task:
      elasticcommonfields: {}
      id: c08ef6f1-f7e8-498e-8a55-7ad1ea21aabd
      version: -1
      name: Get local snapshots list
      description: Returns all local snapshots.
      script: '|||tanium-tr-list-local-snapshots'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "10":
    id: "10"
    taskid: 6363c407-d17c-4dbc-812f-6807794be3a9
    type: regular
    task:
      elasticcommonfields: {}
      id: 6363c407-d17c-4dbc-812f-6807794be3a9
      version: -1
      name: Get labels list
      description: Returns all available labels in the system.
      script: '|||tanium-tr-list-labels'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      limit: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "11":
    id: "11"
    taskid: 7c9ec308-5754-49e5-8748-ee08458cffab
    type: title
    task:
      elasticcommonfields: {}
      id: 7c9ec308-5754-49e5-8748-ee08458cffab
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1580
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "12":
    id: "12"
    taskid: d2b1dd27-91e9-4729-8ce5-495842ff6db2
    type: regular
    task:
      elasticcommonfields: {}
      id: d2b1dd27-91e9-4729-8ce5-495842ff6db2
      version: -1
      name: Get alert by ID
      description: Returns alert object based on ID.
      script: '|||tanium-tr-get-alert-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      alert-id:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 865
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "13":
    id: "13"
    taskid: 764d80cb-90a6-4a68-8b19-2af4b05c4e4d
    type: regular
    task:
      elasticcommonfields: {}
      id: 764d80cb-90a6-4a68-8b19-2af4b05c4e4d
      version: -1
      name: Update alert state
      description: Update the state of a single alert.
      script: '|||tanium-tr-alert-update-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      alert-id:
        simple: "1"
      state:
        simple: Resolved
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 690
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "14":
    id: "14"
    taskid: 5963eef9-db52-41cf-8310-b7d91b7f641d
    type: condition
    task:
      elasticcommonfields: {}
      id: 5963eef9-db52-41cf-8310-b7d91b7f641d
      version: -1
      name: Validate alert state
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "15"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: Tanium.Alert.State
            iscontext: true
          right:
            value:
              simple: Resolved
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1040
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "15":
    id: "15"
    taskid: ebd1c5ff-f7d8-4b4e-8d39-b19ae1b6c5cf
    type: regular
    task:
      elasticcommonfields: {}
      id: ebd1c5ff-f7d8-4b4e-8d39-b19ae1b6c5cf
      version: -1
      name: Update alert state
      description: Update the state of a single alert.
      script: '|||tanium-tr-alert-update-state'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "17"
    scriptarguments:
      alert-id:
        simple: "1"
      state:
        simple: Unresolved
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1215
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "16":
    id: "16"
    taskid: f40685af-01f0-4992-89e1-98f836256ef8
    type: regular
    task:
      elasticcommonfields: {}
      id: f40685af-01f0-4992-89e1-98f836256ef8
      version: -1
      name: Get connection by name
      description: Returns a connection object based on name.
      script: '|||tanium-tr-get-connection-by-name'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      connection-name:
        simple: ip-172-31-44-5.eu-central-1.compute.internal
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1565
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "17":
    id: "17"
    taskid: b93bd3ce-3986-4ae3-8ccb-cfff78240ec6
    type: regular
    task:
      elasticcommonfields: {}
      id: b93bd3ce-3986-4ae3-8ccb-cfff78240ec6
      version: -1
      name: Get label by ID
      description: Returns label object based on ID.
      script: '|||tanium-tr-get-label-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      label-id:
        simple: "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1390
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "18":
    id: "18"
    taskid: 80938970-7cc1-45cf-8451-69e437f16220
    type: title
    task:
      elasticcommonfields: {}
      id: 80938970-7cc1-45cf-8451-69e437f16220
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2460
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "20":
    id: "20"
    taskid: 1020e641-dd2a-4558-83f2-34ee3dc56fca
    type: regular
    task:
      elasticcommonfields: {}
      id: 1020e641-dd2a-4558-83f2-34ee3dc56fca
      version: -1
      name: Get file events by connection
      description: Queries events for a connection.
      script: '|||tanium-tr-list-events-by-connection'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "22"
    scriptarguments:
      connection-name:
        simple: local-EC2AMAZ-KGMRO60-2020_02_09T13.39.59.431Z.db
      event-type:
        simple: Process
      fields: {}
      filter: {}
      limit: {}
      match: {}
      offset: {}
      sort: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1915
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "21":
    id: "21"
    taskid: 67026d04-a417-4cc9-8cbf-2a4e7b53f908
    type: regular
    task:
      elasticcommonfields: {}
      id: 67026d04-a417-4cc9-8cbf-2a4e7b53f908
      version: -1
      name: tanium-tr-create-connection
      description: Creates a local or remote connection.
      script: Tanium Threat Response|||tanium-tr-create-connection
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "20"
    scriptarguments:
      connection-timeout: {}
      destination:
        simple: '`EC2AMAZ - KGMRO60-2020_02_09T13.39.59.431Z.db`'
      destination-type:
        simple: computer_name
      remote:
        simple: "False"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1740
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "22":
    id: "22"
    taskid: dbebc722-14e8-4939-8795-ce2090c73810
    type: regular
    task:
      elasticcommonfields: {}
      id: dbebc722-14e8-4939-8795-ce2090c73810
      version: -1
      name: tanium-tr-get-process-info
      description: Get information for a process.
      script: Tanium Threat Response|||tanium-tr-get-process-info
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      connection-name:
        simple: local-EC2AMAZ-KGMRO60-2020_02_09T13.39.59.431Z.db
      ptid:
        simple: "667692"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2095
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "23":
    id: "23"
    taskid: 798f019b-bf69-4f63-8de3-40e9dcfd0ea2
    type: regular
    task:
      elasticcommonfields: {}
      id: 798f019b-bf69-4f63-8de3-40e9dcfd0ea2
      version: -1
      name: tanium-tr-get-evidence-by-id
      description: Retrive the evidence by it's ID.
      script: Tanium Threat Response|||tanium-tr-get-evidence-by-id
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      evidence-id:
        simple: "29"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 2275
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2475,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
