id: f9cec181-90bf-4b61-8f2c-1f6b76c38bb2
version: -1
contentitemfields:
  propagationLabels:
  - all
name: Tanium Threat Response - Request File Download
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: d8c82418-fe27-4e68-880d-a871016a49af
    type: start
    task:
      id: d8c82418-fe27-4e68-880d-a871016a49af
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "1":
    id: "1"
    taskid: 37898cab-ef34-4cb2-8120-77459d73ec0a
    type: regular
    task:
      id: 37898cab-ef34-4cb2-8120-77459d73ec0a
      version: -1
      name: tanium-tr-request-file-download
      description: Request a new file download
      script: Tanium Threat Response|||tanium-tr-request-file-download
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      connection-id:
        simple: ${inputs.connection-id}
      path:
        simple: ${inputs.path}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "2":
    id: "2"
    taskid: 0c9aa392-4a09-4d29-8c3a-07a49de57bd7
    type: playbook
    task:
      id: 0c9aa392-4a09-4d29-8c3a-07a49de57bd7
      version: -1
      name: GenericPolling
      description: |-
        Use this playbook as a sub-playbook to block execution of the master playbook until a remote action is complete.
        This playbook implements polling by continuously running the command in Step \#2 until the operation completes.
        The remote action should have the following structure:

        1. Initiate the operation.
        2. Poll to check if the operation completed.
        3. (optional) Get the results of the operation.
      playbookName: GenericPolling
      type: playbook
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      AdditionalPollingCommandArgNames:
        simple: host,path
      AdditionalPollingCommandArgValues:
        simple: ${inputs.connection-id},${inputs.path}
      Ids:
        complex:
          root: Tanium
          accessor: FileDownload.ID
      Interval:
        simple: "1"
      PollingCommandArgName:
        simple: date
      PollingCommandName:
        simple: tanium-tr-get-download-file-request-status
      Timeout:
        simple: "10"
      dt:
        simple: Tanium.DownloadFileRequest(Status!='Completed').ID
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "3":
    id: "3"
    taskid: 544e1dad-1998-4feb-84e9-d6d564ffb89e
    type: title
    task:
      id: 544e1dad-1998-4feb-84e9-d6d564ffb89e
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "4":
    id: "4"
    taskid: b4d7ff47-6cb3-4395-87fb-8e404a3903cd
    type: regular
    task:
      id: b4d7ff47-6cb3-4395-87fb-8e404a3903cd
      version: -1
      name: tanium-tr-create-connection
      description: Creates a local or remote connection.
      script: Tanium Threat Response|||tanium-tr-create-connection
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      connection-timeout: {}
      destination:
        simple: ${inputs.connection-id}
      destination-type:
        simple: ${inputs.destination-type}
      remote:
        simple: "True"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "5":
    id: "5"
    taskid: 3f60da64-6615-4342-881e-dfbaa0321ae8
    type: regular
    task:
      id: 3f60da64-6615-4342-881e-dfbaa0321ae8
      version: -1
      name: tanium-tr-delete-connection
      description: Delete a connection by connection name.
      script: Tanium Threat Response|||tanium-tr-delete-connection
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      connection-name:
        simple: ${inputs.connection-id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "6":
    id: "6"
    taskid: a8bf4a48-e1b1-4b70-86de-2029191db32d
    type: regular
    task:
      id: a8bf4a48-e1b1-4b70-86de-2029191db32d
      version: -1
      name: Get connection by name
      description: Returns a connection object based on name.
      script: Tanium Threat Response|||tanium-tr-get-connection-by-name
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "7"
    scriptarguments:
      connection-name:
        simple: ${inputs.connection-id}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "7":
    id: "7"
    taskid: 0f4cff77-fcf3-476d-8d82-882ede2aba3a
    type: condition
    task:
      id: 0f4cff77-fcf3-476d-8d82-882ede2aba3a
      version: -1
      name: Is connection active?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "1"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: Tanium
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: Tanium.Connection.Name
                      iscontext: true
                    right:
                      value:
                        simple: inputs.connection-id
                      iscontext: true
                accessor: Connection.State
            iscontext: true
          right:
            value:
              simple: active
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "8":
    id: "8"
    taskid: 85c86dac-494b-45e0-8f8b-57c96feaac15
    type: condition
    task:
      id: 85c86dac-494b-45e0-8f8b-57c96feaac15
      version: -1
      name: Delete connection?
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "3"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: inputs.delete-connection
            iscontext: true
          right:
            value:
              simple: "true"
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
  "9":
    id: "9"
    taskid: 777b5dc2-7f7f-4d44-84ff-def483e11cf5
    type: regular
    task:
      id: 777b5dc2-7f7f-4d44-84ff-def483e11cf5
      version: -1
      name: Get downloaded file
      description: Get the actual content of a downloaded file by file ID.
      script: Tanium Threat Response|||tanium-tr-get-downloaded-file
      type: regular
      iscommand: true
      brand: Tanium Threat Response
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      file-id:
        simple: ${Tanium.FileDownloadRequest.ID}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 162.5,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quiet: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1610,
        "width": 492.5,
        "x": 50,
        "y": 50
      }
    }
  }
inputs:
- key: connection-id
  value: {}
  required: true
  description: Connection ID.
  playbookInputQuery: null
- key: destination-type
  value: {}
  required: true
  description: 'Type of destination: ip_address or computer_name.'
  playbookInputQuery: null
- key: path
  value: {}
  required: true
  description: Path of file.
  playbookInputQuery: null
- key: download-file
  value:
    simple: "true"
  required: false
  description: If true, the file will be downloaded, otherwise, only a file download
    object will be created.
  playbookInputQuery: null
- key: delete-connection
  value:
    simple: "true"
  required: false
  description: If true, the connection will be deleted in the end of the playbook,
    otherwise, it will remain open.
  playbookInputQuery: null
outputs: []
