name: Docs Deploy
on: 
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          TEST: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$GITHUB_CONTEXT"
          if [[ "$TEST" == TEST* ]]; then
            echo "secret is present"
          else
            echo "no secret"
          fi
      - name: Deploy Docs
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
        run: |
          echo "comparing before: $BEFORE to $AFTER"
          git diff --name-only $BEFORE...$AFTER
          echo "HEAD:"
          git rev-parse --abbrev-ref HEAD
          echo "remotes: "
          git remote -v
          echo "git log"
          git log --stat --max-count=10 
